[package]
name = "bifm-index"
version = "0.1.0"
edition = "2024"

[dependencies]
fm-index-benchmarking = { path = "src/fm-index-extensions" }
fm-index = { path = "deps/fm-index" }
vers-vecs = { path = "deps/vers-vecs" }
libsais64-rs = { path = "../libsais64-rs" }
bytelines = "2.5.0"
postcard = { version = "1.1.1", features = ["alloc"] }
serde = { version = "1.0.197", features = ["derive"] }
sa-index = { path = "../sa-index" }
